#!/usr/bin/env ruby

require 'nokogiri'
require 'fileutils'

`respec2html --src ./_external/aria-practices/aria-practices.html --out ./_includes/aria-practices.html`

# Fix examples
target_path = 'aria-practices'
FileUtils.mkdir_p(target_path)
Dir.chdir(target_path) do  
  FileUtils.ln_s('../_external/aria-practices/examples', 'examples', force: true)
end

# Write included HTML files
index = File.open("./_includes/aria-practices.html") { |f| Nokogiri::HTML(f) }
body_html = index.xpath('//body')
nav_html = body_html.search('//nav').remove.first
nav_html.search('h2').remove
nav_html.prepend_child('<header id="tocheading" class="box-h box-h-simple box-h-full"> Page Contents</header>')
nav_html['class'] = "box box-simple box-full"
nav_html['aria-labelledby'] = "tocheading" 
body_html.search("//div[@class='head']").remove
body_html.search("//section[@id='sotd']").remove
body_html.search("//section[@id='sotd']").remove
abstract_html = body_html.search("//section[@id='abstract']").remove
abstract_html.search('h2').remove

File.open('./_includes/abstract.html', 'w') { |file| file.write(abstract_html) }
File.open('./_includes/toc.html', 'w') { |file| file.write(nav_html) }
File.open('./_includes/body.html', 'w') { |file| file.write(body_html) }
